### ISSUE TITLE
数据集中doc目录为空

### ISSUE THREAD

**Issue by haha744** [Asichurter/MalFusionFSL#1]
作者您好，在模型复现的过程中，config目录下的reloadAllTestConfig函数，在测试阶段需要加载对应任务在doc目录下的train.json文件，例如：virushare-20/doc/322/train.json，但是在数据集中该目录下未见包含内容，请问可否共享各任务下的train与test文件？

**Comment by Asichurter** [comment]
你好，doc目录下的均为运行记录，doc/322实际上是运行`run/train.py`之后，根据`config/train.json`中的配置产生的实验运行记录保存位置。因此数据集不会包含这个。

要完整地运行实验，你需要先配置`config/train.json`和`config/test.json`，然后先运行`run/train.py`来进行模型训练，脚本会自动创建`doc/[version]`文件夹，然后运行`run/test.py`进行测试。复现时，按照文中的参数配置json参数文件即可。

**Comment by haha744** [comment]
好的，感谢！
