### ISSUE TITLE
请求原始的cuckoo分析报告

### ISSUE THREAD

**Issue by 123yonghu** [Asichurter/MalFusionFSL#2]
作者您好，请问您还保存的有原始的cuckoo分析报告吗，我现在要进行的项目需要用到动态执行api序列的运行参数，返回值等信息，您的原始的cuckoo分析报告将会对我的项目产生很大的帮助，可以请您分享一下吗，感激不尽。

**Comment by Asichurter** [comment]
你好。关于API调用的参数，当时在运行Cuckoo的时候由于虚拟机硬盘非常有限，所以修改了Cuckoo代码添加了一个结果后处理步骤，在这个步骤中丢弃了除了API调用名称以外的所有信息，包括调用参数。所以实际上我手中的源数据也不包含API调用参数信息。很抱歉。

**Comment by 123yonghu** [comment]
谢谢，没关系。您的项目对我的帮助很大，还好您这里提供了原始的PE文件，能让我重新复现。
